---
title             : |
  Title here
shorttitle        : "Short title here"
author            : |
  Joseph V. Casillas<p>Rutgers University</p>joseph.casillas@rutgers.edu
  
bibliography      : "./bib/os_refs.bib"
csl               : "./bib/apa-6th-edition.csl"
indent: true

format:
  docx:
    reference-doc: "./ref_doc/apa_style.docx"
    number-sections: false
    highlight-style: github
    code-line-numbers: true
    fig-align: center
    tbl-colwidths: true

editor_options: 
  markdown: 
    wrap: sentence
metadata: 
  subject: linguistics
  description: "Open science practices"
  category: article
---

```{r}
#| label: setup
#| include: false

# Set document defaults
knitr::opts_chunk$set(
  cache.extra = knitr::rand_seed, 
  fig.retina = 2, 
  echo = F, 
  message = F, 
  warning = F,
  fig.asp = 0.5625,
  out.width = "100%",
  dpi = 300, 
  fig.path = 'figs/', 
  dev = c("png", "pdf")
  )
```

{{< pagebreak >}}

# Abstract {.unnumbered}

Abstract here

*Keywords:* Bayesian Data Analysis, Statistics, Quantitative Methods, Uncertainty, Inference

*Word count:* xxx

{{< pagebreak >}}

# `r rmarkdown::metadata$title`

```{r}
#| child: "./sections/0_introduction.qmd"
```

```{r}
#| child: "./sections/1_what-is-open-science.qmd"
```

```{r}
#| child: "./sections/2_open-data.qmd"
```

```{r}
#| child: "./sections/3_positionality-statements.qmd"
```

```{r}
#| child: "./sections/4_preregistration.qmd"
```

```{r}
#| child: "./sections/5_reproducible-code-projects.qmd"
```

```{r}
#| child: "./sections/6_preprints.qmd"
```

```{r}
#| child: "./sections/7_conclusion.qmd"
```

{{< pagebreak >}}

# References {.unnumbered}

::: {#refs}
:::
