---
config:
  theme: base
  themeVariables:
    primaryTextColor: '#000'  
    primaryColor: '#DEF5E5FF' 
    secondaryColor: '#B7E6C5FF'
    tertiaryColor: '#84D9B1FF' 
    fontSize: '13px'
    fontFamily: 'Times New Roman, Times, serif'
---
mindmap
  root((**Open science**))
    **Stance**
      (Positionality statements)
      (Declaration of<br>conflicts of interest)
      (Decision to share materials)
    **Workflow**
      (Literate programming)
      (Reproducible code/projects)
      (Shareable environments)
    **Dissemination**
      (Preregistration)
      (Registered reports)
      (Pre-prints)
      ("Publish materials<br>(data, code, stimuli, etc.)")