---
format: gfm
---

# figs

Last update: `r Sys.Date()`  

This directory contains all of the figures included in the manuscript. 

```{r}
#| label: dir
#| echo: false

fs::dir_tree(regexp = ".rmarkdown", invert = TRUE)
```

## Additional info

- credit
  - figure generated in `./main.qmd`
  - both .png and .pdf files available
  - vectorized file is uploaded to journal website
  - represents each author's self-evaluation with regard to the Contributor Role Taxonomy (CRediT: <https://credit.niso.org>)
- dissemination-cycle
  - figure generated via mermaid in `./main.qmd`
  - touched up in photoshop (.psd) because colors didn't look right
  - .png is file included in manuscript
- os-flow
  - figure generated via mermaid in `./main.qmd`
  - touched up in photoshop (.psd) because colors didn't look right
  - .png is file included in manuscript
- preprints
  - figure generated in `./main.qmd`
  - both .png and .pdf files available
  - vectorized file is uploaded to journal website
- preregistration
  - figure generated in `./main.qmd`
  - both .png and .pdf files available
  - vectorized file is uploaded to journal website
