---
title: "Untitled"
format: docx
---

A positionality statement is a reflective piece of writing that acknowledges researchers' stance - or position - toward a research topic, framework, and even participants. One's positionality encompasses their social, cultural, and personal identity, as well as their biases and assumptions (Holmes, 2020), and can influence how research is done and how results are interpreted (Rowe, 2014). Among others, relevant personal characteristics that may be included in a positionality statement are gender and racial identity, age, sexual orientation, immigration status, ideological stances (Berger, 2013). These traits may indirectly impact research endeavors, since participants may be more willing to engage in a study if they perceive the researcher as sympathetic (De Tona, 2006, as cited in Berger, 2013) or may even offer different responses based on the researcher's perceived identity (Berger, 2013). While positionality statements have been adopted in some disciplines of the humanities and social sciences as a way of recognizing the various ways in which researchers' backgrounds and identities may intersect with their research endeavors, they are a relatively new incorporation in the field of linguistics, appearing primarily in subfields such as applied linguistics, linguistic anthropology, and linguistic ethnography (Bucholtz et al., 2023).  
Increasingly, positionality statements are considered crucial components of the research process, as they increase transparency into research practices (Steltenphohl et al., 2022) and contextualize the environment in which studies take place, or, in other words, "[define] the boundaries within which research was produced" (Jafar, 2018, p. 1).  While traditionally, positionality statements have been more prevalent in qualitative research, they should be considered equally important in quantitative research, since, aside from contributing to ongoing efforts to promote transparency and openness in research practices, recognizing and addressing the researcher's positionality can increase the validity of the findings (Jafar, 2018). Moreover, Bucholtz et al. (2023) note that, considering researchers' positionality may be especially important in linguistics, "which relies on racially minoritized communities as sources of data yet lack adequate (if any) representation of those communities among faculty researchers" (p. 2). 
However, although many researchers support and advocate for the inclusion of positionality statements in their research publications (e.g., Jafar, 2018; Steltenphohl et al., 2022; Bucholtz et al., 2023), others are contesting this practice, pointing to the universalism of research or, in other words, the belief that scholarly endeavors should be assessed on their inherent merits, regardless of the status or personal identity of the person making the contribution (Savolainen et al., 2023). Additionally, Savolainen et al. (2023) draw connections between positionality statements and conflict of interest statements, arguing that, while researchers are required to disclose any and all financial gains associated with a research project, "positionality statements grant authors the freedom to decide which parts of their biography they choose to share and how they choose to frame it." (p. 1334). 

While positionality statements, due to their reflexive nature, may encompass larger pieces of writing, they can also take the form of short paragraphs that illustrate a few personal characteristics deemed relevant for the particular research endeavor: "Gabriela is a white immigrant cis-gender woman from Romania whose research focuses on how non-native speakers are ideologically framed as linguistically deficient in comparison to native speakers characterized by their linguistic authority and expertise."
Lastly, in showing their commitment to Diversity, Equity, Inclusivity, and Belonging (DEIB) initiatives, journals have started to encourage authors to include positionality statements with their submissions (see the Journal of Social and Personal Relationships). Therefore, researchers should reflect on their positionality before starting a project and write a positionality statement. When submitting a study for publication, the positionality statement can be included in additional materials if the word limit is a concern. 
In sum, positionality statements are critical in linguistic research as they promote critical self-reflection, increase transparency, and help address diversity and inclusion concerns. Additionally, including positionality statements in quantitative research can increase the validity of findings. By reflecting on who it is that does the research, linguistics can become a more diverse, inclusive, and transparent field. 

References:
Berger, R. (2013). Now I see it, now I don't: researcher's position and reflexivity in qualitative research. Qualitative Research, 15(2), 219-234. https://doi.org/10.1177/1468794112468475  
Bucholtz, M., Campbell, E. W., Cevallos, T., Cruz, V., Fawcett, A. Z., Guerrero, B., Lydon, K., Mendoza, I. G., Peters, S. L., & Reyes Basurto, G. (2023). Researcher positionality in linguistics: Lessons from undergraduate experiences in community-centered collaborative research. Language & Linguistics Compass, e12495. https://doi.org/10.1111/lnc3.12495 
Holmes, A.G.D. (2020). Researcher Positionality - A Consideration of Its Influence and Place in Qualitative Research - A New Researcher Guide. Shanlax International Journal of Education, 8(4), 1-10.
Jafar, A. (2018). What is positionality and should it be expressed in quantitative studies? Emergency Medicine Journal, 35(5), 232-324.
Rowe, W. E. (2014). Positionality. In D. Coghlan & M. Brydon-Miller (Eds.), The Sage Encyclopedia of Action Research, Sage
Savolainen, J.; Casey, P.J.; McBrayer, J.P.; Schwerdtle, P.N. (2023). Positionality and Its Problems: Questioning the Value of Reflexivity Statements in Research. Perspectives on Psychological Science, 18(6), 1331-1338
Steltenpohl, C., Hudson, S., & Klement, K. (2022, February 8). How to begin writing a positionality statement [Video]. Vimeo. https://vimeo.com/675236573/741e24aab7

