---
format: gfm
---

# data

Last update: `r Sys.Date()`  

This directory contains the `raw` and `tidy` data directories. 

```{r}
#| label: dir
#| echo: false

fs::dir_tree(regexp = ".rmarkdown", invert = TRUE)
```

## raw

- This directory contains csv files with preprocessed data about registered reports pulled from the OSF framework. 
- Every time the data are scraped a new version is included
- The files follow the following format: 
  - year-month-day_registered_reports
  - followed by either `raw.csv` or `2raw.csv`
  - the latter represents a more updated version of the data set (i.e., it includes more journals), but it is incomplete in that is does not contain all of the same columns as `raw.csv`
  - The most up-to-date files are combined, made tidy in `./main.qmd` and stored in the `tidy` direectory, e.g., `2024-12-14_registered_reports.csv`

## tidy

- This directory contains all the tidy csv files, which include: 
  - x_registered_reports.csv
  - x_preprints_osf.csv
  - x_preregistrations_osf.csv
- Muliple version exist of some of the files, depending on when the data were scraped
- The `x` in the file names above represent the date the data were obtained (y-m-d format)
- All data sets are loaded from `./main.qmd`
