---
format: gfm
---

# docs

Last update: `r Sys.Date()`  

This directory contains the `pre-print` and `submissions` directories. 

```{r}
#| label: dir
#| echo: false

fs::dir_tree(regexp = ".rmarkdown", invert = TRUE)
```

## pre-print

- This directory contains the `docx` and `pdf` versions of the manuscript
- The numbers represent the day (ymd) the file was uploaded to psyarxiv

## submissions

- This directory contains subdirectories that are named based on the date and version of the project
- The subdirectories contain submissions (ending in `_vX`) and response letters (ending in `_rX`)
  - Submission subdirectories contain the anonymized manuscript, title page, and corresponding figures that were uploaded the to journal website for each version
  - Response letter subdirectories contain the comments from the editor and anonymous reviewers (labelled `reviewer_x.Rmd`), as well as the author response (`main.Rmd`)
  - Depending on the guidelines of the journal, response letters and reviewer comments may be included in the `.gitignore` file, i.e., they may *not* be publicly available
